### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by SjorsWijsman** [ralfz123/web-app-from-scratch-2021#1]
## Repo
- [x]  **Is there a repo description at the top?**
- [x] **Is the repo open to issues?**
- [x] **Does it include a gitignore**
* Staat er in, nog niet gebruikt (ook nog niet echt nodig; geen node_modules of .ds_store files in de repo)
- [x] **Is the concept described well in the readme?**
* Vette Readme, ziet er goed uit! 
- [x] **Is the API described in the readme?**
* Yes en variabelen & data structuur beschreven

## Code
- [ ] **Try to understand the code flow**
* Code flow ziet er goed uit. Kan nog opgedeeld worden in modules; hierdoor kan je ook voorkomen dat je twee keer een fetch function hebt (`getData()` en `getDataTwo()`). Maak hier bijvoorbeeld 1 function van die de url (naar de api) en een callback function om de data te handlen ontvangt als arguments.
- [x] **Check the code against our course's best practices**
* Er staan nog een aantal variabelen in de global scope: `endpoint`, `endpointTwo` & `likeButton`. 
* Modules zoals hierboven beschreven.
* (Nog) geen manipulatie van de data, maar dat is ook niet echt nodig dus idk.
* Aantal plekken waar je `const` ipv `let` kan gebruiken
- [x] **Check the code for consistency, is code being written the same way in different places?**
* Ziet er consistent uit! Goed consistent gebruik van `''`, `camelCase`, etc.
- [x] **Does the code follow naming conventions? Do variable and function names make sense to you?**
* Variable & function names geschreven in `camelCase`. Namen als `getData` en `getDataTwo` kunnen misschien beter beschrijven wat voor data ze ophalen (bijvoorbeeld `getCatImg` en `getJoke`). Ziet er verder goed uit!

Lekker bezig man 👍

**Comment by ralfz123** [comment]
Thanks voor de feedback Sjors!
Ik ga inderdaad nog kijken naar het async fetchen van data, hoe ik dat het best en mooist kan doen. Daarbij wil ook gebruik gaan maken van modules. Variabelen die in de global scope staan horen natuurlijk bij de fetch, die ga ik namelijk nog omschrijven.

Thanks! 🔥  🔥  🔥
