### ISSUE TITLE
Code review week 2

### ISSUE THREAD

**Issue by RobinFrugte97** [ralfz123/web-app-from-scratch-2021#11]
Hey Ralf!

Sterk concept! Als ik een nieuwe combo laad, gooit ie m'n favourites leeg. Hoort dat? Voor de rest kun je misschien kijken of het duidelijk is voor dat gebruiker dat je favourites kan uitkiezen. Misschien iets meer toelichting of de plek van je favourite knop veranderen. Kijk maar.

Lekkere readme man! Je plaatjes werken alleen niet.

Actor diagram is lekker overzichtelijk en goed te volgen qua vormgeving. Alleen lijkt het nu dat je van App naar Router gaat, maar er gaat geen pijl verder naar bvb API. Ook komt er niks bij render terecht, er gaat alleen wat uit. Om je vragen te beantwoorden, kijk even naar de diagrams van [Jochem](https://github.com/jochemvogel/web-app-from-scratch-2021/blob/master/README.md), 
 vooral zijn interaction diagram is sterk. Ik zou localstorage er inderdaad in verwerken. Zorg dat beide diagrams overeen komen met de flow van je website en de structuur van je code. Daar wordt naar gekeken.

Gooi de examples nog even uit je repo, wordt het wat cleaner van.

Je codestructuur is goed! Alles is lekker overzichtelijk en goed leesbaar. Goeie modules ook!

Kijk nog wel even naar het waterval effect wat je nu hebt in je code. De ene functie gaat over in de andere functie. Je roept bijvoorbeeld render aan in je fetch functie. Het zou netter zijn als je het resultaat uit je fetch returnt naar je main, waar je het vervolgens mee kan geven aan je render functie.

Kijk ook nog even naar waar je je variabelen declareert. Bijvoorbeeld in je detailPage.js, waarom declareer je de elementen niet binnen de functies waar je de bijbehorende eventlistener aanmaakt? Dan vervuil je je globalscope niet.

Kijk ook of je buttons om naar je favourites te gaan in links kan veranderen. Dat is semantisch correct én het zorgt ervoor dat je router werkt zoals het eigenlijk zou moeten. Kijk eens naar hoe [Jochem](https://github.com/jochemvogel/web-app-from-scratch-2021/blob/master/js/router/router.js) routie gebruikt. Je wilt dat routie vanuit je url werkt, niet vanuit eventlisteners.

Kijk nog even goed naar de rubric om te checken of je alles hebt.

Lekker bezig! Ga zo door man

**Comment by ralfz123** [comment]
Dankjewel voor de feedback Robin! Ik moet nog localstorage toevoegen aan  mijn applicatie. De andere feedbackpunten zijn inderdaad zeer relevant voor mij , dankjewel!
