### ISSUE TITLE
You could use a vendor file for external scripts

### ISSUE THREAD

**Issue by suustenvoorde** [ralfz123/web-app-from-scratch-2021#12]
https://github.com/ralfz123/web-app-from-scratch-2021/blob/bc2dcbc0856d9bc5c4f7bee0acad79ac8182b973/scripts/modules/router/routie.js#L8

**Comment by ralfz123** [comment]
Thanks for the feedback! I'll make a vendor file :) Now I see it's a lot cleaner.
