### ISSUE TITLE
Feedback 01-03

### ISSUE THREAD

**Issue by sreen020** [ralfz123/web-app-from-scratch-2021#15]
Yo Ralf, je repo en eindproduct zien er goed uit! Hier nog een aantal kleine tips voor het eindgesprek.

README
Ziet er goed uit!
- Haal dingen weg of vul ze aan die op dit moment nog onnodig zijn, denk aan Challenges / Inventions en je todo lijst.
- Misschien is het mooi om de code van je map() te laten zien ipv allen vertellen dat je die gebruikt hebt

CODE
- Goede, duidelijke comments 
- Je code is netjes gesplitst in kleine bestanden
- Haal de nog gecommente code weg
- Je hebt nog meerdere console.logs in je code staan

LIVE APP
- Wanneer ik 10 posts bekijk en niets heb geliked staat er niks in mijn favorite (gewenst gedrag) maar wanneer ik de 11e like worden ze alle 11 in mijn favorite gezet.
- The info button op de favorite pagina werkt niet helemaal goed. Ik krijg elke keer dezelfde grap, namelijk de laatst gelikte.
- Wanneer ik een post wil verwijderen wordt altijd de bovenste post verwijdert ipv de post waar ik op klik.
- Je kan meerdere keren dezelfde post liken

**Comment by ralfz123** [comment]
Hey Sjoerd,

Dankjewel voor je feedback! Erg handig allemaal! En bij de live app feedback, dat klopt allemaal. Dat is nog even in productie. Dat hoop ik voor morgen af te kunnen ronden. Thanks man!
