### ISSUE TITLE
getData DRY

### ISSUE THREAD

**Issue by shabier** [ralfz123/web-app-from-scratch-2021#2]
Deze functie roep je twee keer op! Als het niet anders mogelijk is, kan je deze functie opnieuw schrijven met een 2e argument dat wisselt voor de beide API endpoints. 

https://github.com/ralfz123/web-app-from-scratch-2021/blob/497317f00f712d08c714829e0402b60fa75ea762/scripts/main.js#L11
https://github.com/ralfz123/web-app-from-scratch-2021/blob/497317f00f712d08c714829e0402b60fa75ea762/scripts/main.js#L24

**Comment by ralfz123** [comment]
Thanks man!
Ik ga de async manier van fetchen toepassen, dus dan zal dit vervallen inderdaad :)
