### ISSUE TITLE
Unused function

### ISSUE THREAD

**Issue by shabier** [ralfz123/web-app-from-scratch-2021#3]
https://github.com/ralfz123/web-app-from-scratch-2021/blob/497317f00f712d08c714829e0402b60fa75ea762/scripts/main.js#L42

**Comment by ralfz123** [comment]
Goed gezien, maar ik gebruik deze functie wel met de [reload button](https://github.com/ralfz123/web-app-from-scratch-2021/blob/master/index.html#L17) in de html, ik heb daar als attribuut onlcick meegegeven met als waarde de functie reloadPage zodat hij daarop triggert. Ik ga zeker nog even kijken of ik deze feature wel in mijn app ga verwerken.

``` html
<button onclick="reloadPage()">Another combo!</button>
```
