### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by shabier** [ralfz123/web-app-from-scratch-2021#4]
Alle element object declarations kunnen eigenlijk bovenin je js bestand, kijk even waar je de elementen aanmaakt voor je het bovenin zet, anders krijg je undefined!

https://github.com/ralfz123/web-app-from-scratch-2021/blob/497317f00f712d08c714829e0402b60fa75ea762/scripts/main.js#L1

**Comment by ralfz123** [comment]
Top! Dankjewel, ik wil wel globale variabelen vermijden. Overigens is hetgeen wat nu bovenaan staat stappen die ik maak voor het data fetchen.
