### ISSUE TITLE
Check function

### ISSUE THREAD

**Issue by shabier** [ralfz123/web-app-from-scratch-2021#5]
Deze functie zou je weg kunnen laten en het gelijk in de eventlistener oppakken met de `Event` (ik denk dat je deze ook gaat gebruiken)

https://github.com/ralfz123/web-app-from-scratch-2021/blob/497317f00f712d08c714829e0402b60fa75ea762/scripts/main.js#L51

**Comment by ralfz123** [comment]
Top, dankjewel! Dat kan ik zeker doen!
