### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by RowinRuizendaal** [ralfz123/web-app-from-scratch-2021#6]
Hmm eerste wat ik zo snel zie: Je main.js bevat nog best veel functies die aparte modules kunnen worden zoals fetchdata die je bijvoorbeeld in een module map utils of w/e kan zetten. 

Er is een verschil tussen base url en endpoint url, je hebt 2x een const met de naam endpoint :) 

De directe execute van getdata in main js is een beetje raar omdat je eerst de functie callt terwijl hij paar regels daar onder staat. 

Je wilt eigenlijk dat een module of functie altijd iets returned, probeer op basis van return iets te doen :) als dat niet kan dan is het maar zo maar probeer het. Wellicht een idee om al je module in aparte mappen te zetten met een benaming zodat het logischer is. 

Ik zie dat je soms let gebruikt terwijl je daar ook const kan gebruiken.

**Comment by ralfz123** [comment]
Thanks Rowin, hier ga ik zeker mee aan de slag! :)
