### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/web-app-from-scratch-2021#8]
**Algemeen:**

- In je README linken ze nog naar `/blob/master`. Hier moet je nog even de juiste URL plaatsen
- Volgens mij heb je inmiddels wat meer modules en is het diagram niet helemaal meer up to date? (zoals `deleteFav`, `detailPage`). `render.js` is ook leeg. Denk dat je daar nog wel naar kan kijken.

**Actor Diagram**:
- Het lijkt net of `fetchData()` onder **API** nergens wordt aangeroepen als ik naar het diagram kijk. 
- Parameter bij `renderData(` onder **RENDER** wordt niet gesloten 😉

**Interaction Diagram**:
- Ligt het aan mij of is deze half weggevallen?
- Zelfde geldt hier voor die `renderData(` functie.
- Die **yes** & **no** staan er nog niet zo lekker in. Denk dat het slim is dat deze dingen op een andere plek zet, zodat ze meer leesbaar zijn.

**Comment by ralfz123** [comment]
Dankjewel voor je feedback Jochem! Ik heb inderdaad de diagrams nog niet helemaal zoals ik ze wil hebben. Wat bedoel je met het eerste puntje van /blob/master?

🚀 🚀 🚀

**Comment by jochemvogel** [comment]
> Dankjewel voor je feedback Jochem! Ik heb inderdaad de diagrams nog niet helemaal zoals ik ze wil hebben. Wat bedoel je met het eerste puntje van /blob/master?
> 
> 🚀 🚀 🚀

![image](https://user-images.githubusercontent.com/34123512/107754061-3bd38b80-6d21-11eb-935b-ee5349986136.png)
Waar deze naartoe linken 🙂

**Comment by ralfz123** [comment]
Oja, dat klopt hoor. Daar moeten nog images staat :). Thanks voor de reminder ;)
