### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by jochemvogel** [ralfz123/web-app-from-scratch-2021#9]
Als ik jou was, zou ik gewoon alle starter files van de main repo verwijderen. Alle `course`, `docs`, `examples` etc. Hebben niet echt een meerwaarde als je het mij vraagt.

Daarnaast zal ik de `favicon.svg` gewoon in de `assets` zetten. Wellicht nog `assets/img` folder maken, maar is voor nu (weinig assets) niet nodig lijkt mij.

Ten slotte zou ik `router.js` opsplitsen.[ Kijk hoe ik het gedaan heb](https://github.com/jochemvogel/web-app-from-scratch-2021/tree/master/js/utils/router). In feite heb jij niets van Routie geschreven en kun je deze dus het best in een aparte file doen en importeren in `router.js`.

Voor de rest: prima en nice README!

**Comment by ralfz123** [comment]
Lekkere feedback man, heb ik zeker wat aan en ga ik zeker ook verwerken! Die router.js is nog een dingetje inderdaad, maar daar ik ga mij even doorheen stoeien. Thanks Jochem!

🚀 🚀 🚀
